# Generated by Django 5.2.13 on 2026-04-14 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiwakeDenpyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('denpyo_no', models.CharField(editable=False, max_length=25, unique=True, verbose_name='伝票番号')),
                ('denpyo_type', models.CharField(choices=[('SHIWAKE', '仕訳'), ('FURIKAE', '振替')], default='SHIWAKE', max_length=10, verbose_name='伝票種別')),
                ('date', models.DateField(verbose_name='伝票日付')),
                ('keijo_date', models.DateField(blank=True, help_text='会計帳簿に反映する日付。空欄の場合は伝票日付と同じ扱い。', null=True, verbose_name='計上日付')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('is_locked', models.BooleanField(default=False, verbose_name='ロック済')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denpyo_set', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '仕訳伝票',
                'verbose_name_plural': '仕訳伝票',
                'ordering': ['-date', '-denpyo_no'],
            },
        ),
        migrations.CreateModel(
            name='ShiwakeMeisai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('row_no', models.PositiveSmallIntegerField(default=0, help_text='User-defined ordering within the voucher.', verbose_name='行番号')),
                ('kari_kashi', models.CharField(choices=[('KA', '借方'), ('SHI', '貸方')], max_length=3, verbose_name='借/貸')),
                ('kingaku', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='金額')),
                ('tekyou', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('bumon', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.bumonmaster', verbose_name='部門')),
                ('denpyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meisai', to='journal.shiwakedenpyo', verbose_name='伝票')),
                ('hojo', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.hojokamokumaster', verbose_name='補助科目')),
                ('kamoku', models.ForeignKey(limit_choices_to={'is_active': True, 'level': 4}, on_delete=django.db.models.deletion.PROTECT, to='master.kanjokamokumaster', verbose_name='勘定科目')),
                ('torihikisaki', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.torihikisakimaster', verbose_name='取引先')),
                ('zei_kubun', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.zeimaster', verbose_name='税区分')),
            ],
            options={
                'verbose_name': '仕訳明細',
                'verbose_name_plural': '仕訳明細',
                'ordering': ['row_no', 'kari_kashi', 'id'],
            },
        ),
    ]
