# Generated by Django 5.2.13 on 2026-04-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiwakedenpyo',
            name='keijo_date',
        ),
        migrations.AlterField(
            model_name='shiwakedenpyo',
            name='memo',
            field=models.CharField(blank=True, max_length=200, verbose_name='摘要（全体）'),
        ),
        migrations.AlterField(
            model_name='shiwakemeisai',
            name='row_no',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='行番号'),
        ),
    ]
