# Generated by Django 5.2.12 on 2026-04-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiwakedenpyo',
            options={'ordering': ['-date', '-denpyo_no'], 'verbose_name': '仕訳伝票', 'verbose_name_plural': '仕訳伝票'},
        ),
        migrations.RenameField(
            model_name='shiwakedenpyo',
            old_name='hiduke',
            new_name='date',
        ),
    ]
