# Generated by Django 5.2.12 on 2026-04-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_shiwakedenpyo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiwakemeisai',
            name='kingaku',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='金額'),
        ),
    ]
