# Generated by Django 5.2.12 on 2026-04-10 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_shiwakemeisai_kingaku'),
        ('master', '0004_alter_torihikisakimaster_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiwakemeisai',
            name='torihikisaki',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.torihikisakimaster', verbose_name='取引先'),
        ),
    ]
