# Generated by Django 5.2.12 on 2026-04-10 01:39

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Admins')
    Group.objects.get_or_create(name='Accountants')
    Group.objects.get_or_create(name='Viewers')

def revert_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Admins', 'Accountants', 'Viewers']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_groups, revert_groups),
    ]
