# Generated by Django 5.2.12 on 2026-03-30 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BumonMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='部門コード')),
                ('name', models.CharField(max_length=100, verbose_name='部門名')),
                ('manager_name', models.CharField(blank=True, max_length=100, verbose_name='担当者名')),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='年間予算')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('order_no', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '部門',
                'verbose_name_plural': '部門マスタ',
                'ordering': ['order_no', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TorihikiSakiMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='取引先コード')),
                ('name', models.CharField(max_length=200, verbose_name='取引先名')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '取引先',
                'verbose_name_plural': '取引先マスタ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ZeiMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('zei_kubun', models.CharField(choices=[('STANDARD', '課税（標準税率10%）'), ('REDUCED', '課税（軽減税率8%）'), ('EXEMPT', '非課税'), ('FREE', '免税'), ('OUTSIDE', '対象外')], max_length=20, unique=True, verbose_name='税区分コード')),
                ('zei_name', models.CharField(max_length=100, verbose_name='税区分名')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='税率(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='適用開始日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='適用終了日')),
                ('order_no', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '税区分',
                'verbose_name_plural': '消費税率マスタ',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='KanjoKamokuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='科目コード')),
                ('name', models.CharField(max_length=100, verbose_name='科目名')),
                ('level', models.PositiveSmallIntegerField(blank=True, verbose_name='レベル')),
                ('taisha_kubun', models.CharField(choices=[('SHISAN', '資産'), ('FUSAI', '負債'), ('JUNSHISAN', '純資産'), ('SHUEKI', '収益'), ('HIYO', '費用')], max_length=20, verbose_name='科目属性（貸借区分）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.kanjokamokumaster', verbose_name='親科目')),
            ],
            options={
                'verbose_name': '勘定科目',
                'verbose_name_plural': '勘定科目マスタ',
                'ordering': ['code'],
            },
        ),
    ]
