# Generated by Django 5.2.12 on 2026-04-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjokamokumaster',
            name='taisha_kubun',
            field=models.CharField(blank=True, choices=[('SHISAN', '資産'), ('FUSAI', '負債'), ('JUNSHISAN', '純資産'), ('SHUEKI', '収益'), ('HIYO', '費用')], max_length=20, verbose_name='科目属性（貸借区分）'),
        ),
    ]
