# Generated by Django 5.2.13 on 2026-04-20 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bumonmaster',
            options={'ordering': ['code'], 'verbose_name': '部門マスタ', 'verbose_name_plural': '部門マスタ'},
        ),
        migrations.AlterModelOptions(
            name='hojokamokumaster',
            options={'ordering': ['kamoku__code', 'code'], 'verbose_name': '補助科目マスタ', 'verbose_name_plural': '補助科目マスタ'},
        ),
        migrations.AlterModelOptions(
            name='kanjokamokumaster',
            options={'ordering': ['code'], 'verbose_name': '勘定科目マスタ', 'verbose_name_plural': '勘定科目マスタ'},
        ),
        migrations.AlterModelOptions(
            name='torihikisakimaster',
            options={'ordering': ['code'], 'verbose_name': '取引先マスタ', 'verbose_name_plural': '取引先マスタ'},
        ),
        migrations.AlterModelOptions(
            name='zeimaster',
            options={'ordering': ['order_no'], 'verbose_name': '税マスタ', 'verbose_name_plural': '税マスタ'},
        ),
        migrations.AddField(
            model_name='hojokamokumaster',
            name='furigana',
            field=models.CharField(blank=True, help_text='ローマ字検索用', max_length=100, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='kanjokamokumaster',
            name='furigana',
            field=models.CharField(blank=True, help_text='ローマ字検索用', max_length=100, verbose_name='フリガナ'),
        ),
        migrations.AlterField(
            model_name='hojokamokumaster',
            name='code',
            field=models.CharField(max_length=10, verbose_name='補助科目コード'),
        ),
        migrations.AlterField(
            model_name='kanjokamokumaster',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='勘定科目コード'),
        ),
        migrations.AlterField(
            model_name='kanjokamokumaster',
            name='name',
            field=models.CharField(max_length=100, verbose_name='勘定科目名'),
        ),
        migrations.AlterField(
            model_name='kanjokamokumaster',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.kanjokamokumaster', verbose_name='親勘定科目'),
        ),
        migrations.AlterField(
            model_name='kanjokamokumaster',
            name='taisha_kubun',
            field=models.CharField(blank=True, choices=[('SHISAN', '資産'), ('FUSAI', '負債'), ('JUNSHISAN', '純資産'), ('SHUEKI', '収益'), ('HIYO', '費用')], max_length=20, verbose_name='貸借区分'),
        ),
        migrations.AlterField(
            model_name='zeimaster',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='税率（%）'),
        ),
    ]
