# Generated by Django 5.2.12 on 2026-04-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_kanjokamokumaster_taisha_kubun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeimaster',
            name='zei_kubun',
        ),
    ]
