# Generated by Django 5.2.13 on 2026-04-20 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_bumonmaster_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiwakeDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, verbose_name='辞書名')),
                ('shortcut_code', models.CharField(blank=True, max_length=10, verbose_name='検索キー')),
                ('tekiyou', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('bumon', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.bumonmaster', verbose_name='部門')),
                ('kari_hojo', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dict_kari_hojo', to='master.hojokamokumaster', verbose_name='借方補助')),
                ('kari_kamoku', models.ForeignKey(limit_choices_to={'is_active': True, 'level': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='dict_kari_kamoku', to='master.kanjokamokumaster', verbose_name='借方科目')),
                ('kari_zei', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dict_kari_zei', to='master.zeimaster', verbose_name='借方税区分')),
                ('kashi_hojo', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dict_kashi_hojo', to='master.hojokamokumaster', verbose_name='貸方補助')),
                ('kashi_kamoku', models.ForeignKey(limit_choices_to={'is_active': True, 'level': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='dict_kashi_kamoku', to='master.kanjokamokumaster', verbose_name='貸方科目')),
                ('kashi_zei', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dict_kashi_zei', to='master.zeimaster', verbose_name='貸方税区分')),
                ('torihikisaki', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.torihikisakimaster', verbose_name='取引先')),
            ],
            options={
                'verbose_name': '仕訳辞書',
                'verbose_name_plural': '仕訳辞書',
                'ordering': ['shortcut_code', 'name'],
            },
        ),
    ]
