# Generated by Django 5.2.13 on 2026-04-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_shiwakedictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeimaster',
            name='tax_rate',
            field=models.IntegerField(default=0, verbose_name='税率（%）'),
        ),
    ]
