# Generated by Django 5.2.12 on 2026-04-10 01:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_zeimaster_zei_kubun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torihikisakimaster',
            name='name',
            field=models.CharField(max_length=100, verbose_name='取引先名'),
        ),
        migrations.AlterField(
            model_name='zeimaster',
            name='valid_from',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1))], verbose_name='適用開始日'),
        ),
        migrations.AlterField(
            model_name='zeimaster',
            name='valid_to',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2100, 12, 31))], verbose_name='適用終了日'),
        ),
    ]
