# Generated by Django 5.2.13 on 2026-04-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_zeimaster_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeimaster',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='税率（%）'),
        ),
    ]
